[profile.default]
src = 'contracts'
out = 'artifactsFoundry'
libs = ['node_modules', 'lib']
test = 'testFoundry'
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'forge-std/=lib/forge-std/src/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config